### ISSUE TITLE
Default OpenWRT install does not contain whoami

### ISSUE THREAD

**Issue by casept** [chmduquesne/wg-ip#3]
On my OpenWRT system `whoami` is not part of the default install, which results in
```shell
./wg-ip: line 758: whoami: not found
```
when trying to run the utility.

You can easily remove the dependency by checking the `$USER` env variable instead of calling the utility to check whether the user is root.

**Comment by chmduquesne** [comment]
Thanks for the feedback! I will fix that asap.
